# Fichier : api-docs/swagger.yaml

openapi: 3.0.0
info:
  # Le titre de votre API, visible en haut de la page de documentation
  title: API Plateforme Citoyenne 910
  # La description générale de ce que fait l'API
  description: |-
    Cette API gère toutes les données de la plateforme de mobilisation citoyenne.
    Elle permet de gérer les actions, les utilisateurs, les données géographiques (via GEE),
    les revendications et d'interagir avec le chatbot IA.
  version: 1.0.0

# "paths" est la liste de toutes les URLs (endpoints) de votre API
paths:
  # Endpoint pour récupérer la liste des actions
  /api/actions:
    get:
      # Un résumé court de ce que fait l'endpoint
      summary: Récupère la liste de toutes les actions de mobilisation.
      # Une description plus détaillée. C'est ici que vous mettez vos "commentaires".
      description: |
        Retourne un tableau JSON contenant toutes les actions planifiées ou en cours.
        Chaque action possède un ID, un titre, une date, un lieu et un type.
      # Mots-clés pour regrouper les endpoints dans l'interface Swagger
      tags:
        - Actions
      responses:
        # Décrit la réponse si tout se passe bien (code 200)
        '200':
          description: Une liste d'actions a été retournée avec succès.
          content:
            application/json:
              schema:
                type: array
                items:
                  # Vous pouvez définir ici la structure d'un objet "Action"
                  type: object

  # Endpoint pour créer une nouvelle action
  /api/actions/create:
    post:
      summary: Crée une nouvelle action.
      description: Ajoute une nouvelle action à la base de données. Nécessite une authentification.
      tags:
        - Actions
      requestBody:
        description: L'objet action à créer.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: "Blocage du rond-point de la Victoire"
                date:
                  type: string
                  format: date-time
                  example: "2025-09-10T08:00:00Z"
      responses:
        '201':
          description: Action créée avec succès.